local trainstationutil = require "modules/trainstationutil"

function data()

return { 
	availability = {
		yearFrom = 1910,
	    yearTo = 1930,
	},
	cost = {
		price = 18000,
	},

	description = {
		name = _("name1900b"),
		description = _("desc1900b"),
		icon = "ui/construction/station/rail/modular_station/1900b_holz.tga"
	},
	-- buildMode = "MULTI",
	type = "track",
	order = {
		value = 250,
	},
	metadata = {
		track = true,
	},

	--buildMode = "MULTI",
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, 1)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end
