local transf = require "transf"
local vec3 = require "vec3"
local modulesutil = require "modulesutil"
local trainstationutil = require "modules/trainstationutil"

function data()

return { 
	availability = {
		yearFrom = 1925,
		yearTo = 1930,
	},
	cost = {
		price = 18000,
	},

	description = {
		name = _("name_s25_1"),
		description = _("desc_s25_1"),
		icon = "ui/construction/station/rail/modular_station/stahl_s25_1.tga"
	},
	-- buildMode = "MULTI",
	type = "track",
	order = {
		value = 250,
	},
	metadata = {
		track = true,
	},

	--buildMode = "MULTI",
	
	updateFn = function(result, transform, tag, slotId, addModuleFn, params)
		trainstationutil.makeTrack(result, transform, tag, slotId, addModuleFn, params, 1)
	end,
	
	getModelsFn = function()
		
		local result = {
		}
		
		return result
	end
}

end